// src/permissions.js
const allPermissions = [
  "viewDashboard",
  "viewProduct",
  "createProduct",
  "editProduct",
  "deleteProduct",
  "viewCustomer",
  "createCustomer",
  "editCustomer",
  "deleteCustomer",
  "viewEmployee",
  "createEmployee",
  "editEmployee",
  "deleteEmployee",
  "viewIngredient",
  "createIngredient",
  "editIngredient",
  "deleteIngredient",
  "viewRecipe",
  "createRecipe",
  "editRecipe",
  "deleteRecipe",
  "createOrder",
  "manageStock",
  "viewReports",
  "processPayment",
  "viewAmbiente",
  "createAmbiente",
  "editAmbiente",
  "deleteAmbiente",
  "viewTable",
  "createTable",
  "editTable",
  "deleteTable",
  "viewReservation",
  "createReservation",
  "editReservation",
  "deleteReservation",
  "manageIfoodAuth",
  "createCategory",
  "viewCategory",
  "editCategory",
  "deleteCategory",
  "addUser",
  "manageSalesGoals",
  "viewTeamMembers",
  "manageOrder",
  "configSystem",
  "viewOrder",
  "viewOrders",
  "manageCaixa",
  "createQueue",
  "viewQueue",
  "manageNfe",
  "viewSupplier",
  "createSupplier",
  "editSupplier",
  "deleteSupplier",
  "administrator",

    
  // Adicione todas as outras permissões aqui
];

module.exports = allPermissions;
